plugins {
    id("com.gradleup.shadow") version "8.3.6"
    id 'java'
}

group = 'pl.norbit'
version = '1.9.0'

repositories {
    mavenCentral()
    maven {
        name = "spigotmc-repo"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/'
    }
    maven {
        url = 'https://jitpack.io'
    }
    maven {
        name "nexomcReleases"
        url "https://repo.nexomc.com/releases"
    }
    maven {
        name = "matteodev"
        url = "https://maven.devs.beer/"
    }
    maven {
        url = "https://nexus.phoenixdevt.fr/repository/maven-public/"
    }
    maven {
        url = "https://repo.momirealms.net/releases/"
    }
    maven {
        url = "https://mvn.lumine.io/repository/maven-public/"
    }
    maven {
        url = "https://repo.oraxen.com/releases"
    }
}

shadowJar {
    archiveClassifier.set("")

    configurations = [project.configurations.runtimeClasspath]

    relocate("org.bstats", "${project.group}.libs.bstats")
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT"

    //bstats
    implementation("org.bstats:bstats-bukkit:3.2.1")

    //placeholderapi
    compileOnly 'me.clip:placeholderapi:2.11.6'

    //lombok
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    //SuperVanish
    compileOnly 'com.github.LeonMangler:SuperVanish:6.2.18-3'

    //custom
    compileOnly("beer.devs:itemsadder-api:4.0.18-beta-9")
    compileOnly("com.nexomc:nexo:1.24.0")
    compileOnly("io.th0rgal:oraxen:1.163.0:dev")
    compileOnly("io.lumine:MythicLib-dist:1.6.2-SNAPSHOT")
    compileOnly("net.Indyuce:MMOItems-API:6.9.5-SNAPSHOT")
    compileOnly("net.momirealms:craft-engine-core:26.7.1")
    compileOnly("net.momirealms:craft-engine-bukkit:26.7.1")
    compileOnly("io.lumine:MythicCrucible-API:5.13.0-SNAPSHOT")
    compileOnly("io.lumine:Mythic-Dist:5.12.1")
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
