#---------------------------------------------------------------------------------#
#                                                                                 #
#      _____                    _            _ _______                 _          #
#    / ____|                  (_)          | |__   __|               | |          #
#   | (___  _   _ _ ____   __  ___   ____ _| |  | |_      _____  __ _| | _____    #
#   \___ \| | | | '__\ \ / / | \ \ / / _` | |  | \ \ /\ / / _ \/ _` | |/ / __|    #
#    ____) | |_| | |   \ V /  | |\ V / (_| | |  | |\ V  V /  __/ (_| |   <\__ \   #
#   |_____/ \__,_|_|    \_/   |_| \_/ \__,_|_|  |_| \_/\_/ \___|\__,_|_|\_\___/   #
#                                                                                 #
#---------------------------------------------------------------------------------#

# SurvivalTweaks by Norbit4

# github: https://github.com/Norbit4/
# modrinth: https://modrinth.com/user/norbit
# spigot: https://www.spigotmc.org/resources/authors/norbittech.392197/
# builtbybit: https://builtbybit.com/creators/n0rbit.98575/

# If you like the plugin, support me with a positive opinion <3

# Need support?
# wiki: https://n0rbit.gitbook.io/wiki/resources/survivaltweaks
# Join to discord: https://discord.com/invite/DPXqQcDDTs

#---------------------------------------#
#               [Config]                #
#---------------------------------------#

# The Plugin supports Minecraft 1.21.11 with Paper or forks.
# Spigot and Bukkit are not supported.

debug: false

commands:
  sign: 'sign'