name: SurvivalTweaks
version: '${version}'
main: pl.norbit.survivaltweaks.SurvivalTweaks
api-version: '1.20'
authors: [Norbit4]
website: https://github.com/Norbit4
description: 'This plugin is created to add some useful mechanics for useless items in Minecraft.'
softdepend:
  - PlaceholderAPI
commands:
  survivaltweaks:
    description: 'Main command for SurvivalTweaks plugin'
    usage: '/survivaltweaks <reload>'
    permission: 'survivaltweaks.command'
    aliases: [st]
  track:
    description: 'Track location'
    usage: '/track <x, z>'
    permission: 'survivaltweaks.track'